[build]
command = "npm run build"
publish = "build"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"

[build.processing]
skip_processing = false

[[plugins]]
package = "@netlify/plugin-lighthouse"

[build.processing.html]
pretty_urls = true

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.images]
compress = true

[forms]
[forms.contact]
name = "contact"
